### ISSUE TITLE
GitHub - Folder Structure

### ISSUE THREAD

**Issue by jwood36** [MinZhong7/Task-1_UML#1]
Remove the 'folder' text from the end of the top-level folders

- [x] doc folder
- [x] rss folder
- [x] src folder

**Comment by MinZhong7** [comment]
I moved all folders from repository TASK-1_UML to forked repository CIS255_Vehicle when I submitted Final Homework TASK#2 because I didn't realize the issues remain here. What a stupid girl, hahaha! To solve issues here, I moved back all folders I had already modified for the last submission, that is, removed the 'folder' text from the end of the top-level folders. Now you can see three folders called "doc," "rss," and "src."
