### ISSUE TITLE
UML - Design

### ISSUE THREAD

**Issue by jwood36** [MinZhong7/Task-1_UML#8]
You need to redesign your Diagram to reflect your chosen Model.

You chose the 'Type' model (Coupe, Sedan, SUV, Truck), so you need to have 1 Page per 'Type'

On each Page, you need to have one Class representation (with members from the Excel document) showing inheritance to that Page's Type.

- [x] UML - Design: Coupe
- [x] UML - Design: Sedan
- [x] UML - Design: SUV
- [x] UML - Design: Truck

**Comment by MinZhong7** [comment]
I redesigned the Diagram to 'Make' model (Chevrolet, Ford, Honda, Hyundai and Toyota) because I wanted to do Make model originally but I thought it is Type model. 
I have 1 Page per 'Make' and on each Page, I have one Class representation (with members from the Excel document) showing inheritance to that Page's Type.

 UML - Design: Chevrolet
 UML - Design: Ford
 UML - Design: Honda
 UML - Design: Hyundai
 UML - Design: Toyota
